In [1]:
import pandas as pd
import numpy as np

In [7]:
df=pd.read_csv('Proji - Sheet1.csv')

In [8]:
df.head()

,Дата,Score,Уровень,Lead Score,Продажи и Клиентский сервис,Рутинные процессы,Данные и База знаний,Операционка и Прогнозы,Культура и Готовность команды,Сильная зона,...,UTM Content,UTM Term,Referrer,Landing Path,Device,Language,Ответы (JSON),Обратная связь (JSON),ID,ID.1
0,"14.06.2026, 22:41:26",100,leader,35,100,100,100,100,100.0,ai,...,NaN,NaN,NaN,/,desktop,ru,"{""q1"":10,""q2"":10,""q3"":10,""q4"":10,""q5"":10,""q6"":...",NaN,NaN,NaN
1,"14.06.2026, 23:16:16",94,leader,35,77,100,100,100,100.0,ai,...,NaN,NaN,NaN,/result?data=%7B%22segment%22%3A%7B%22industry...,desktop,ru,"{""q1"":3,""q2"":10,""q3"":10,""q4"":10,""q5"":10,""q6"":1...",NaN,NaN,NaN
2,"14.06.2026, 23:31:13",100,leader,35,100,100,100,100,100.0,ai,...,NaN,NaN,https://proji-quiz-66hp4jcgs-akbooos-projects....,/,desktop,ru,"{""q1"":10,""q2"":10,""q3"":10,""q4"":10,""q5"":10,""q6"":...",NaN,NaN,NaN
3,"14.06.2026, 23:53:42",100,leader,20,100,100,100,100,100.0,ai,...,NaN,NaN,NaN,/,desktop,ru,"{""q1"":10,""q2"":10,""q3"":10,""q4"":10,""q5"":10,""q6"":...",NaN,NaN,NaN
4,"15.06.2026, 12:14:25",76,leader,82,57,57,85,100,100.0,ai,...,NaN,NaN,NaN,/,desktop,ru,"{""q1"":0,""q2"":7,""q3"":10,""q4"":4,""q5"":3,""q6"":10,""...",NaN,NaN,NaN

In [9]:
df=df[df['Дата']>'19.06.2026']
df

,Дата,Score,Уровень,Lead Score,Продажи и Клиентский сервис,Рутинные процессы,Данные и База знаний,Операционка и Прогнозы,Культура и Готовность команды,Сильная зона,...,UTM Content,UTM Term,Referrer,Landing Path,Device,Language,Ответы (JSON),Обратная связь (JSON),ID,ID.1
39,2026-06-18T16:03:58.330Z,100,AI-Лидер,100,b2b_services,100+,b2b,scaling,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,2026-06-18T16:06:42.516Z,100,AI-Лидер,100,0,0,0,0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,{},"{""f1"":3,""f2"":4,""f3"":3}",NaN,NaN
49,"19.06.2026, 13:13:02",37,point_potential,55,85,0,0,25,38.0,sales_support,...,NaN,NaN,NaN,/,desktop,ru,"{""q1"":10,""q2"":5,""q3"":10,""q4"":0,""q5"":0,""q6"":4,""...",NaN,sub_1781856757267_i8pygg2td,NaN
50,"19.06.2026, 13:20:38",49,point_potential,45,100,0,30,25,52.0,sales_support,...,NaN,NaN,NaN,/,desktop,ru,"{""q1"":10,""q2"":5,""q3"":10,""q4"":0,""q5"":3,""q6"":4,""...",NaN,sub_1781857207828_9756a9xpf,NaN
51,"19.06.2026, 13:22:47",39,point_potential,55,75,0,30,25,40.0,sales_support,...,NaN,NaN,NaN,/result?data=%7B%22submissionId%22%3A%22sub_17...,desktop,ru,"{""q1"":10,""q2"":0,""q3"":10,""q4"":0,""q5"":3,""q6"":10,...",NaN,sub_1781857354201_zwsg3b23f,NaN
52,"19.06.2026, 13:24:59",80,ai_leader,40,50,100,100,85,82.0,data_knowledge,...,NaN,NaN,NaN,/result?data=%7B%22submissionId%22%3A%22sub_17...,desktop,ru,"{""q1"":7,""q2"":10,""q3"":0,""q4"":10,""q5"":10,""q6"":4,...",NaN,sub_1781857480613_hdj5b5mbj,NaN
53,"19.06.2026, 14:26:26",47,point_potential,35,35,40,40,40,58.0,culture_ready,...,NaN,NaN,https://vercel.com/,/,desktop,ru,"{""q1"":7,""q2"":4,""q3"":0,""q4"":4,""q5"":4,""q6"":4,""q7...","{""f1"":4,""f2"":4,""f3"":2}",sub_1781861146313_h6tnk9a1b,NaN
54,"19.06.2026, 14:28:23",49,point_potential,55,70,40,0,70,44.0,predictive_ops,...,NaN,NaN,NaN,/,mobile,ru,"{""q1"":4,""q2"":0,""q3"":7,""q4"":4,""q5"":0,""q6"":4,""q7...","{""f1"":4,""f2"":3,""f3"":2}",sub_1781861282896_phyoizith,NaN
55,"19.06.2026, 16:31:34",40,point_potential,15,40,100,40,20,36.0,automation,...,NaN,NaN,NaN,/quiz,mobile,ru,"{""q1"":7,""q2"":0,""q3"":4,""q4"":10,""q5"":4,""q6"":4,""q...",NaN,sub_1781868587180_edr9ikvtf,NaN
56,"19.06.2026, 16:31:52",86,ai_leader,40,70,100,100,70,94.0,data_knowledge,...,NaN,NaN,NaN,/quiz,mobile,ru,"{""q1"":7,""q2"":10,""q3"":4,""q4"":10,""q5"":10,""q6"":10...",NaN,sub_1781868585492_txxjr162g,NaN
57,"19.06.2026, 16:32:06",68,transformation,25,20,100,70,100,68.0,predictive_ops,...,NaN,NaN,NaN,/quiz,mobile,ru,"{""q1"":10,""q2"":10,""q3"":0,""q4"":10,""q5"":7,""q6"":0,...",NaN,sub_1781868585085_6o9pqtwnw,NaN
58,"19.06.2026, 16:32:29",77,ai_leader,40,40,100,100,85,80.0,data_knowledge,...,NaN,NaN,NaN,/quiz,mobile,ru,"{""q1"":10,""q2"":10,""q3"":4,""q4"":10,""q5"":10,""q6"":1...",NaN,sub_1781868587555_14apinzgh,NaN
59,"19.06.2026, 16:32:33",57,transformation,45,50,70,40,55,62.0,automation,...,NaN,NaN,NaN,/quiz,mobile,ru,"{""q1"":4,""q2"":7,""q3"":0,""q4"":7,""q5"":4,""q6"":10,""q...",NaN,sub_1781868587938_00dqs8dxj,NaN
60,"19.06.2026, 16:32:43",69,transformation,35,35,70,70,70,82.0,culture_ready,...,NaN,NaN,NaN,/quiz,mobile,ru,"{""q1"":10,""q2"":10,""q3"":0,""q4"":7,""q5"":7,""q6"":4,""...",NaN,sub_1781868584952_qj364nehj,NaN
61,"19.06.2026, 16:35:08",75,ai_leader,25,70,100,70,85,70.0,automation,...,NaN,NaN,NaN,/quiz,mobile,ru,"{""q1"":10,""q2"":4,""q3"":4,""q4"":10,""q5"":7,""q6"":4,""...",NaN,sub_1781868608455_fv5dwg8xd,NaN
62,"19.06.2026, 16:35:15",47,point_potential,45,50,40,0,35,62.0,culture_ready,...,NaN,NaN,NaN,/quiz,mobile,ru-RU,"{""q1"":10,""q2"":4,""q3"":0,""q4"":4,""q5"":0,""q6"":7,""q...",NaN,sub_1781868894919_hb3epbzi8,NaN
63,"19.06.2026, 16:35:57",71,transformation,35,50,0,100,85,82.0,data_knowledge,...,NaN,NaN,NaN,/quiz,mobile,ru,"{""q1"":10,""q2"":7,""q3"":0,""q4"":0,""q5"":10,""q6"":7,""...",NaN,sub_1781868586788_itu9quu6o,NaN
64,"19.06.2026, 16:37:40",62,transformation,55,50,100,70,85,48.0,automation,...,NaN,NaN,NaN,/quiz,mobile,ru-RU,"{""q1"":7,""q2"":7,""q3"":0,""q4"":10,""q5"":7,""q6"":0,""q...",NaN,sub_1781868599175_gpf0bhtla,NaN
65,"19.06.2026, 19:37:10",64,transformation,55,55,100,100,55,56.0,data_knowledge,...,NaN,NaN,NaN,/quiz,mobile,ru,"{""q1"":7,""q2"":7,""q3"":4,""q4"":10,""q5"":10,""q6"":0,""...",NaN,sub_1781879559559_bwbuqtrvx,NaN
66,"19.06.2026, 19:37:10",64,transformation,55,55,100,100,55,56.0,data_knowledge,...,NaN,NaN,NaN,/quiz,mobile,ru,"{""q1"":7,""q2"":7,""q3"":4,""q4"":10,""q5"":10,""q6"":0,""...",NaN,sub_1781879559559_bwbuqtrvx,NaN
67,"20.06.2026, 01:56:38",59,transformation,25,50,100,70,55,54.0,automation,...,NaN,NaN,NaN,/,desktop,en-GB,"{""q1"":0,""q2"":7,""q3"":0,""q4"":10,""q5"":7,""q6"":10,""...","{""f1"":3,""f2"":3,""f3"":4}",sub_1781862014172_yt4cvmfhh,NaN
68,"20.06.2026, 10:27:59",55,transformation,55,35,70,70,35,64.0,data_knowledge,...,NaN,NaN,NaN,/,mobile,en-GB,"{""q1"":7,""q2"":7,""q3"":0,""q4"":7,""q5"":7,""q6"":4,""q7...","{""f1"":2,""f2"":2,""f3"":2}",sub_1781933252707_r9jssb2wy,NaN
69,"22.06.2026, 12:51:55",64,transformation,25,50,100,70,70,58.0,automation,...,NaN,NaN,NaN,/,mobile,en-GB,"{""q1"":4,""q2"":7,""q3"":0,""q4"":10,""q5"":7,""q6"":4,""q...",NaN,sub_1782114558079_1pc5is8fw,NaN

In [10]:
df=df.iloc[8:]

In [11]:
df

,Дата,Score,Уровень,Lead Score,Продажи и Клиентский сервис,Рутинные процессы,Данные и База знаний,Операционка и Прогнозы,Культура и Готовность команды,Сильная зона,...,UTM Content,UTM Term,Referrer,Landing Path,Device,Language,Ответы (JSON),Обратная связь (JSON),ID,ID.1
55,"19.06.2026, 16:31:34",40,point_potential,15,40,100,40,20,36.0,automation,...,NaN,NaN,NaN,/quiz,mobile,ru,"{""q1"":7,""q2"":0,""q3"":4,""q4"":10,""q5"":4,""q6"":4,""q...",NaN,sub_1781868587180_edr9ikvtf,NaN
56,"19.06.2026, 16:31:52",86,ai_leader,40,70,100,100,70,94.0,data_knowledge,...,NaN,NaN,NaN,/quiz,mobile,ru,"{""q1"":7,""q2"":10,""q3"":4,""q4"":10,""q5"":10,""q6"":10...",NaN,sub_1781868585492_txxjr162g,NaN
57,"19.06.2026, 16:32:06",68,transformation,25,20,100,70,100,68.0,predictive_ops,...,NaN,NaN,NaN,/quiz,mobile,ru,"{""q1"":10,""q2"":10,""q3"":0,""q4"":10,""q5"":7,""q6"":0,...",NaN,sub_1781868585085_6o9pqtwnw,NaN
58,"19.06.2026, 16:32:29",77,ai_leader,40,40,100,100,85,80.0,data_knowledge,...,NaN,NaN,NaN,/quiz,mobile,ru,"{""q1"":10,""q2"":10,""q3"":4,""q4"":10,""q5"":10,""q6"":1...",NaN,sub_1781868587555_14apinzgh,NaN
59,"19.06.2026, 16:32:33",57,transformation,45,50,70,40,55,62.0,automation,...,NaN,NaN,NaN,/quiz,mobile,ru,"{""q1"":4,""q2"":7,""q3"":0,""q4"":7,""q5"":4,""q6"":10,""q...",NaN,sub_1781868587938_00dqs8dxj,NaN
60,"19.06.2026, 16:32:43",69,transformation,35,35,70,70,70,82.0,culture_ready,...,NaN,NaN,NaN,/quiz,mobile,ru,"{""q1"":10,""q2"":10,""q3"":0,""q4"":7,""q5"":7,""q6"":4,""...",NaN,sub_1781868584952_qj364nehj,NaN
61,"19.06.2026, 16:35:08",75,ai_leader,25,70,100,70,85,70.0,automation,...,NaN,NaN,NaN,/quiz,mobile,ru,"{""q1"":10,""q2"":4,""q3"":4,""q4"":10,""q5"":7,""q6"":4,""...",NaN,sub_1781868608455_fv5dwg8xd,NaN
62,"19.06.2026, 16:35:15",47,point_potential,45,50,40,0,35,62.0,culture_ready,...,NaN,NaN,NaN,/quiz,mobile,ru-RU,"{""q1"":10,""q2"":4,""q3"":0,""q4"":4,""q5"":0,""q6"":7,""q...",NaN,sub_1781868894919_hb3epbzi8,NaN
63,"19.06.2026, 16:35:57",71,transformation,35,50,0,100,85,82.0,data_knowledge,...,NaN,NaN,NaN,/quiz,mobile,ru,"{""q1"":10,""q2"":7,""q3"":0,""q4"":0,""q5"":10,""q6"":7,""...",NaN,sub_1781868586788_itu9quu6o,NaN
64,"19.06.2026, 16:37:40",62,transformation,55,50,100,70,85,48.0,automation,...,NaN,NaN,NaN,/quiz,mobile,ru-RU,"{""q1"":7,""q2"":7,""q3"":0,""q4"":10,""q5"":7,""q6"":0,""q...",NaN,sub_1781868599175_gpf0bhtla,NaN
65,"19.06.2026, 19:37:10",64,transformation,55,55,100,100,55,56.0,data_knowledge,...,NaN,NaN,NaN,/quiz,mobile,ru,"{""q1"":7,""q2"":7,""q3"":4,""q4"":10,""q5"":10,""q6"":0,""...",NaN,sub_1781879559559_bwbuqtrvx,NaN
66,"19.06.2026, 19:37:10",64,transformation,55,55,100,100,55,56.0,data_knowledge,...,NaN,NaN,NaN,/quiz,mobile,ru,"{""q1"":7,""q2"":7,""q3"":4,""q4"":10,""q5"":10,""q6"":0,""...",NaN,sub_1781879559559_bwbuqtrvx,NaN
67,"20.06.2026, 01:56:38",59,transformation,25,50,100,70,55,54.0,automation,...,NaN,NaN,NaN,/,desktop,en-GB,"{""q1"":0,""q2"":7,""q3"":0,""q4"":10,""q5"":7,""q6"":10,""...","{""f1"":3,""f2"":3,""f3"":4}",sub_1781862014172_yt4cvmfhh,NaN
68,"20.06.2026, 10:27:59",55,transformation,55,35,70,70,35,64.0,data_knowledge,...,NaN,NaN,NaN,/,mobile,en-GB,"{""q1"":7,""q2"":7,""q3"":0,""q4"":7,""q5"":7,""q6"":4,""q7...","{""f1"":2,""f2"":2,""f3"":2}",sub_1781933252707_r9jssb2wy,NaN
69,"22.06.2026, 12:51:55",64,transformation,25,50,100,70,70,58.0,automation,...,NaN,NaN,NaN,/,mobile,en-GB,"{""q1"":4,""q2"":7,""q3"":0,""q4"":10,""q5"":7,""q6"":4,""q...",NaN,sub_1782114558079_1pc5is8fw,NaN

In [12]:
friday=df.iloc[0:10]

In [17]:
friday

,Дата,Score,Уровень,Lead Score,Продажи и Клиентский сервис,Рутинные процессы,Данные и База знаний,Операционка и Прогнозы,Культура и Готовность команды,Сильная зона,...,Сфера,Размер команды,Модель продаж,Стадия,Landing Path,Device,Language,Ответы (JSON),Обратная связь (JSON),ID
55,"19.06.2026, 16:31:34",40,point_potential,15,40,100,40,20,36.0,automation,...,operations,1-2,b2c,stable,/quiz,mobile,ru,"{""q1"":7,""q2"":0,""q3"":4,""q4"":10,""q5"":4,""q6"":4,""q...",NaN,sub_1781868587180_edr9ikvtf
56,"19.06.2026, 16:31:52",86,ai_leader,40,70,100,100,70,94.0,data_knowledge,...,operations,31-100,mixed,scaling,/quiz,mobile,ru,"{""q1"":7,""q2"":10,""q3"":4,""q4"":10,""q5"":10,""q6"":10...",NaN,sub_1781868585492_txxjr162g
57,"19.06.2026, 16:32:06",68,transformation,25,20,100,70,100,68.0,predictive_ops,...,operations,3-10,b2b,early,/quiz,mobile,ru,"{""q1"":10,""q2"":10,""q3"":0,""q4"":10,""q5"":7,""q6"":0,...",NaN,sub_1781868585085_6o9pqtwnw
58,"19.06.2026, 16:32:29",77,ai_leader,40,40,100,100,85,80.0,data_knowledge,...,operations,11-30,b2b,systemize,/quiz,mobile,ru,"{""q1"":10,""q2"":10,""q3"":4,""q4"":10,""q5"":10,""q6"":1...",NaN,sub_1781868587555_14apinzgh
59,"19.06.2026, 16:32:33",57,transformation,45,50,70,40,55,62.0,automation,...,other,11-30,mixed,stable,/quiz,mobile,ru,"{""q1"":4,""q2"":7,""q3"":0,""q4"":7,""q5"":4,""q6"":10,""q...",NaN,sub_1781868587938_00dqs8dxj
60,"19.06.2026, 16:32:43",69,transformation,35,35,70,70,70,82.0,culture_ready,...,b2b_services,1-2,b2b,systemize,/quiz,mobile,ru,"{""q1"":10,""q2"":10,""q3"":0,""q4"":7,""q5"":7,""q6"":4,""...",NaN,sub_1781868584952_qj364nehj
61,"19.06.2026, 16:35:08",75,ai_leader,25,70,100,70,85,70.0,automation,...,operations,1-2,mixed,early,/quiz,mobile,ru,"{""q1"":10,""q2"":4,""q3"":4,""q4"":10,""q5"":7,""q6"":4,""...",NaN,sub_1781868608455_fv5dwg8xd
62,"19.06.2026, 16:35:15",47,point_potential,45,50,40,0,35,62.0,culture_ready,...,operations,3-10,mixed,systemize,/quiz,mobile,ru-RU,"{""q1"":10,""q2"":4,""q3"":0,""q4"":4,""q5"":0,""q6"":7,""q...",NaN,sub_1781868894919_hb3epbzi8
63,"19.06.2026, 16:35:57",71,transformation,35,50,0,100,85,82.0,data_knowledge,...,other,1-2,partners,scaling,/quiz,mobile,ru,"{""q1"":10,""q2"":7,""q3"":0,""q4"":0,""q5"":10,""q6"":7,""...",NaN,sub_1781868586788_itu9quu6o
64,"19.06.2026, 16:37:40",62,transformation,55,50,100,70,85,48.0,automation,...,operations,11-30,b2b,scaling,/quiz,mobile,ru-RU,"{""q1"":7,""q2"":7,""q3"":0,""q4"":10,""q5"":7,""q6"":0,""q...",NaN,sub_1781868599175_gpf0bhtla

In [18]:
friday.columns

Index(['Дата', 'Score', 'Уровень', 'Lead Score', 'Продажи и Клиентский сервис',
       'Рутинные процессы', 'Данные и База знаний', 'Операционка и Прогнозы',
       'Культура и Готовность команды', 'Сильная зона', 'Слабые зоны', 'Сфера',
       'Размер команды', 'Модель продаж', 'Стадия', 'Landing Path', 'Device',
       'Language', 'Ответы (JSON)', 'Обратная связь (JSON)', 'ID'],
      dtype='object')

In [16]:
friday.drop(columns=['Город', "Имя", 'Телефон', 'Компания', 'Email', 'UTM Source', 'UTM Medium', 'UTM Campaign', 
            'UTM Content', 'UTM Term', 'Referrer', 'ID.1'], inplace=True, axis=1)

C:\Users\Subbota\AppData\Local\Temp\ipykernel_26760\4210416170.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  friday.drop(columns=['Город', "Имя", 'Телефон', 'Компания', 'Email', 'UTM Source', 'UTM Medium', 'UTM Campaign',

In [19]:
friday.to_csv('friday.csv', index=False)

In [20]:
friday.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 55 to 64
Data columns (total 21 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Дата                           10 non-null     object
 1   Score                          10 non-null     int64
 2   Уровень                        10 non-null     object
 3   Lead Score                     10 non-null     int64
 4   Продажи и Клиентский сервис    10 non-null     object
 5   Рутинные процессы              10 non-null     object
 6   Данные и База знаний           10 non-null     object
 7   Операционка и Прогнозы         10 non-null     object
 8   Культура и Готовность команды  10 non-null     float64
 9   Сильная зона                   10 non-null     object
 10  Слабые зоны                    10 non-null     object
 11  Сфера                          10 non-null     object
 12  Размер команды                 10 non-null     object
 13  Модель продаж                  10 non-null     object
 14  Стадия                         10 non-null     object
 15  Landing Path                   10 non-null     object
 16  Device                         10 non-null     object
 17  Language                       10 non-null     object
 18  Ответы (JSON)                  10 non-null     object
 19  Обратная связь (JSON)          0 non-null      object
 20  ID                             10 non-null     object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.7+ KB